# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoauth < Formula
  desc "Command-line interface for NeetoAuth team member management."
  homepage "https://neetoauth.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v0.1.0/neeto-auth-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "e93a00c45d90b9d445e0e12fd3a8bb5a66b18f5edf9ebd2822be789e617343b1"

      def install
        bin.install "neetoauth"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v0.1.0/neeto-auth-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "1806de3404c7f907af2b65dc1b20aba9eedc28aae286ddb8bcdcbba90c03788a"

      def install
        bin.install "neetoauth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v0.1.0/neeto-auth-cli_0.1.0_linux_amd64.tar.gz"
        sha256 "c75667f735c087a76f27ec8f85e4ecdbc807d5ab9c91c9e8d15feeb234e4cf6b"

        def install
          bin.install "neetoauth"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v0.1.0/neeto-auth-cli_0.1.0_linux_arm64.tar.gz"
        sha256 "1a0ad4f4e53c74ccd6c5152d4eecf0be1dd3bc8df99bce6f0ef0c1cfb69405c5"

        def install
          bin.install "neetoauth"
        end
      end
    end
  end
end
