# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetocal < Formula
  desc "NeetoCal CLI — manage your calendar from the terminal"
  homepage "https://neetocal.com"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCal/v1.0.2/neeto-cal-cli_1.0.2_darwin_amd64.tar.gz"
      sha256 "37d9d24d2e28ee4dc902fea7002e85485ebe4f5abb955905946354b6b56ddf7f"

      def install
        bin.install "neetocal"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCal/v1.0.2/neeto-cal-cli_1.0.2_darwin_arm64.tar.gz"
      sha256 "111bba9ce934172d2db9ba486e20e86f5d400f84fbc9e741ed441ede2f2c911c"

      def install
        bin.install "neetocal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCal/v1.0.2/neeto-cal-cli_1.0.2_linux_amd64.tar.gz"
        sha256 "5ac86ed042f68126efa4f259d9258b54c1326f1ff8503b57d271f1a84040a016"

        def install
          bin.install "neetocal"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCal/v1.0.2/neeto-cal-cli_1.0.2_linux_arm64.tar.gz"
        sha256 "b90027c7af90f319c6af2044626e653ab15ea31abc27c752176097083a2e67c8"

        def install
          bin.install "neetocal"
        end
      end
    end
  end
end
