# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoauth < Formula
  desc "Command-line interface for NeetoAuth team member management."
  homepage "https://neetoauth.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v0.1.0/neeto-auth-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "5d3e75650d91765d53eb1b8132b7b555b646de933f32b6f5bb1040dfd86c66ee"

      def install
        bin.install "neetoauth"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v0.1.0/neeto-auth-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "23617bb0b76d6650aa1a0d829d65562564b76638d4b581162cdc461c28687965"

      def install
        bin.install "neetoauth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v0.1.0/neeto-auth-cli_0.1.0_linux_amd64.tar.gz"
        sha256 "d3822b6c862553bf8379f4962ff9d69ded7f7fede272688909eae23db13a6afa"

        def install
          bin.install "neetoauth"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v0.1.0/neeto-auth-cli_0.1.0_linux_arm64.tar.gz"
        sha256 "f8d37682d84f1c149c88adcb55724e77ce771382c195e9c9b046d2978652c392"

        def install
          bin.install "neetoauth"
        end
      end
    end
  end
end
