# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NeetoCalCli < Formula
  desc "NeetoCal CLI — manage your calendar from the terminal"
  homepage "https://neetocal.com"
  version "3.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neetozone/neeto-cal-cli/releases/download/v3.0.0/neeto-cal-cli_3.0.0_darwin_amd64.tar.gz"
      sha256 "fdbca21ae1699b7af7163221e97458a12eebd488c806156a173a5d932ab0203d"

      def install
        bin.install "neetocal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neetozone/neeto-cal-cli/releases/download/v3.0.0/neeto-cal-cli_3.0.0_darwin_arm64.tar.gz"
      sha256 "1607b3018a04cca74274432feebbf05d517f40e9494854d95c38715b0712d934"

      def install
        bin.install "neetocal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/neetozone/neeto-cal-cli/releases/download/v3.0.0/neeto-cal-cli_3.0.0_linux_amd64.tar.gz"
        sha256 "54437f4c44c1444f1a83cb1bed410d50fe1cd725d84a7493e128581ac1f6562f"

        def install
          bin.install "neetocal"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/neetozone/neeto-cal-cli/releases/download/v3.0.0/neeto-cal-cli_3.0.0_linux_arm64.tar.gz"
        sha256 "a131cceaa7275eedc6c279954859457b643c44d4d23a9ba46dd9f72fa809f8aa"

        def install
          bin.install "neetocal"
        end
      end
    end
  end
end
