# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetodesk < Formula
  desc "NeetoDesk CLI"
  homepage "https://neetodesk.com"
  version "1.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoDesk/v1.0.9/neeto-desk-cli_1.0.9_darwin_amd64.tar.gz"
      sha256 "48773417920fd774f3aa6d08669cc8f0a29179b4b94f04da98f16fa5c5374a06"

      def install
        bin.install "neetodesk"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoDesk/v1.0.9/neeto-desk-cli_1.0.9_darwin_arm64.tar.gz"
      sha256 "35fdb1f50aa4bbe55bb2aaad45d32ed0edf45129d54abb197eaa343d3ba8622e"

      def install
        bin.install "neetodesk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoDesk/v1.0.9/neeto-desk-cli_1.0.9_linux_amd64.tar.gz"
        sha256 "8baea5f2f472b9fd35fff8fb1497087026bdc77ff45cf5038e27e1ff4a5165ec"

        def install
          bin.install "neetodesk"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoDesk/v1.0.9/neeto-desk-cli_1.0.9_linux_arm64.tar.gz"
        sha256 "991d86c8ed7e6fde0191470e0627f00e03901998d7f4f36057767d8c9be7aad1"

        def install
          bin.install "neetodesk"
        end
      end
    end
  end
end
