# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoauth < Formula
  desc "Command-line interface for NeetoAuth team member management."
  homepage "https://neetoauth.com"
  version "1.0.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoAuth/v1.0.11/neeto-auth-cli_1.0.11_darwin_amd64.tar.gz"
      sha256 "e926e9530d0416690f9e37386466542ea4a3bab89af638f223dff945bbeb73c2"

      def install
        bin.install "neetoauth"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoAuth/v1.0.11/neeto-auth-cli_1.0.11_darwin_arm64.tar.gz"
      sha256 "335e0cbaf4a8a257915c6df09ff84faa67914c543539d7ca08acc2b0938649bd"

      def install
        bin.install "neetoauth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoAuth/v1.0.11/neeto-auth-cli_1.0.11_linux_amd64.tar.gz"
        sha256 "4bc6c363801d97889b4392070ca3d0fd5969dbf2bfc8bc2b94b313f789531772"

        def install
          bin.install "neetoauth"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoAuth/v1.0.11/neeto-auth-cli_1.0.11_linux_arm64.tar.gz"
        sha256 "44c259851c80a953aa35498c15b1b5a4c9f86b107accbcb0bb0b5f4e332faf88"

        def install
          bin.install "neetoauth"
        end
      end
    end
  end
end
