# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetodeploy < Formula
  desc "NeetoDeploy CLI — manage apps, dynos, addons and deployments from the terminal"
  homepage "https://neetodeploy.com"
  version "3.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoDeploy/v3.6.0/neeto-deploy-cli-go_3.6.0_darwin_amd64.tar.gz"
      sha256 "addcd0ae40733f69d1d4c7f48ca3b60f4ef60a0af74152746c45eb3b61406c0e"

      def install
        bin.install "neetodeploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoDeploy/v3.6.0/neeto-deploy-cli-go_3.6.0_darwin_arm64.tar.gz"
      sha256 "09d3bcbf597d15be3f737176522b698416059ae6b0bed9bef9aa75ff93747569"

      def install
        bin.install "neetodeploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoDeploy/v3.6.0/neeto-deploy-cli-go_3.6.0_linux_amd64.tar.gz"
        sha256 "035d125ff8cb9c628634c15b71a946c627764cc597e8d35008cc95e16947c07f"

        def install
          bin.install "neetodeploy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoDeploy/v3.6.0/neeto-deploy-cli-go_3.6.0_linux_arm64.tar.gz"
        sha256 "b45365fda5eb82e663f38e42c85ca12b067042e0f4d54bda0bd9d9bd3334a1df"

        def install
          bin.install "neetodeploy"
        end
      end
    end
  end
end
