# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoci < Formula
  desc "NeetoCI CLI"
  homepage "https://neetoci.com"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCI/v1.0.5/neeto-ci-cli-v2_1.0.5_darwin_amd64.tar.gz"
      sha256 "8b9754ce37bb98d1ff295caf6475c2fe71e31449b1320259b4e50292f1c449e0"

      def install
        bin.install "neetoci"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCI/v1.0.5/neeto-ci-cli-v2_1.0.5_darwin_arm64.tar.gz"
      sha256 "c243ddfc483aa678867eb8c7f6b7024be5579defcd0a7267bf56de73ab18bc60"

      def install
        bin.install "neetoci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCI/v1.0.5/neeto-ci-cli-v2_1.0.5_linux_amd64.tar.gz"
        sha256 "8d79343e21deb61808552a7b61ce065cfafa64a850b576966d3460f070eeab7f"

        def install
          bin.install "neetoci"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCI/v1.0.5/neeto-ci-cli-v2_1.0.5_linux_arm64.tar.gz"
        sha256 "cc25fc10e3993e333ae65950821e667d7933b85b2df7bbfac4f7cb4892ef680d"

        def install
          bin.install "neetoci"
        end
      end
    end
  end
end
