# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetorecord < Formula
  desc "NeetoRecord CLI"
  homepage "https://neetorecord.com"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoRecord/v1.2.0/neeto-record-cli_1.2.0_darwin_amd64.tar.gz"
      sha256 "6cb574597f528a4e269cbfe4d7c3f4aca8cae11b32ff98ad2d3fd5bce6a005c7"

      def install
        bin.install "neetorecord"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoRecord/v1.2.0/neeto-record-cli_1.2.0_darwin_arm64.tar.gz"
      sha256 "5bf8544aca21c021ee5fa5898b5573182cf8c14be7e7b7a71395ab39a1f9076b"

      def install
        bin.install "neetorecord"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoRecord/v1.2.0/neeto-record-cli_1.2.0_linux_amd64.tar.gz"
        sha256 "5b7fe678efd3c3b60b0bb8e990344d0ccfda82a9c834ad928324dbf348e27c5b"

        def install
          bin.install "neetorecord"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoRecord/v1.2.0/neeto-record-cli_1.2.0_linux_arm64.tar.gz"
        sha256 "7cf73eab1f44f879612dd1157161d28c976cc603ffa5ab5887410593b30b4e11"

        def install
          bin.install "neetorecord"
        end
      end
    end
  end
end
