# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetodeploy < Formula
  desc "NeetoDeploy CLI"
  homepage "https://neetodeploy.com"
  version "3.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoDeploy/v3.4.0/neeto-deploy-cli-go_3.4.0_darwin_amd64.tar.gz"
      sha256 "9b03d4740a478a79873c30f1c36368c8deae356a98178f04533331b25d9e4bbe"

      def install
        bin.install "neetodeploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoDeploy/v3.4.0/neeto-deploy-cli-go_3.4.0_darwin_arm64.tar.gz"
      sha256 "4549bd402b5b460653b5026341799fcc1002c8ac7028fa4025a9daab9e3af918"

      def install
        bin.install "neetodeploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoDeploy/v3.4.0/neeto-deploy-cli-go_3.4.0_linux_amd64.tar.gz"
        sha256 "98440184ba85c9fc42f56210b379862f4932bf144f71e0f801b4f8f92d5b598e"

        def install
          bin.install "neetodeploy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoDeploy/v3.4.0/neeto-deploy-cli-go_3.4.0_linux_arm64.tar.gz"
        sha256 "8c1763e09353844bcccffda81d7da1d34d71ae367f3d60bdac20011c67a4318b"

        def install
          bin.install "neetodeploy"
        end
      end
    end
  end
end
