# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoplanner < Formula
  desc "NeetoPlanner CLI"
  homepage "https://neetoplanner.com"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoPlanner/v0.1.4/neeto-planner-cli_0.1.4_darwin_amd64.tar.gz"
      sha256 "6155f759a6d5aeba0f231d86daf3bfc075b17ff3704f3194d9976c595ad2a67d"

      def install
        bin.install "neetoplanner"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoPlanner/v0.1.4/neeto-planner-cli_0.1.4_darwin_arm64.tar.gz"
      sha256 "e2d57d1c8259b456e6ed1ec4fe847bd93a1b19616269bf81bab081e72cda57ec"

      def install
        bin.install "neetoplanner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoPlanner/v0.1.4/neeto-planner-cli_0.1.4_linux_amd64.tar.gz"
        sha256 "e5dc655550776266cbebe70c97632ecef1c26abac70b63b95bc175074801638e"

        def install
          bin.install "neetoplanner"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoPlanner/v0.1.4/neeto-planner-cli_0.1.4_linux_arm64.tar.gz"
        sha256 "df54e3f3a6226bb0e2deee10bdf898e9a7fe2365e1cfb5b6acd2fad9757afa3f"

        def install
          bin.install "neetoplanner"
        end
      end
    end
  end
end
