# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoengage < Formula
  desc "NeetoEngage CLI"
  homepage "https://neetoengage.com"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoEngage/v1.0.1/neeto-engage-cli_1.0.1_darwin_amd64.tar.gz"
      sha256 "a37411581ecc65fe7eff12684c86a3ecde06c33c4de6b9bcfdb06fdb31ae11de"

      def install
        bin.install "neetoengage"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoEngage/v1.0.1/neeto-engage-cli_1.0.1_darwin_arm64.tar.gz"
      sha256 "37efdbce1425195fcb7e64797df465e02fab4cd9285d06e2788ddf6f6632349a"

      def install
        bin.install "neetoengage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoEngage/v1.0.1/neeto-engage-cli_1.0.1_linux_amd64.tar.gz"
        sha256 "59bddc90a89a31cfe538d7c6371a200253a7a21ac8b218938ace1e43f48bd1be"

        def install
          bin.install "neetoengage"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoEngage/v1.0.1/neeto-engage-cli_1.0.1_linux_arm64.tar.gz"
        sha256 "140b2d46ace1ef104e37f23a2a2741144473fea99f7cb39eff747d78dd359539"

        def install
          bin.install "neetoengage"
        end
      end
    end
  end
end
