# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoplaydash < Formula
  desc "NeetoPlaydash CLI"
  homepage "https://neetoplaydash.com"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v1.0.5/neeto-playdash-cli_1.0.5_darwin_amd64.tar.gz"
      sha256 "bca8cdc4bcf87f8b0a208bf57afc9e3e448a7628242e6cdf85cba3a8c4008f56"

      def install
        bin.install "neetoplaydash"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v1.0.5/neeto-playdash-cli_1.0.5_darwin_arm64.tar.gz"
      sha256 "b173d6397a0bfb3a4135a3ad21c8e1c565fe4b42d1e386a4f34a7bd3aad39e03"

      def install
        bin.install "neetoplaydash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v1.0.5/neeto-playdash-cli_1.0.5_linux_amd64.tar.gz"
        sha256 "0a9742763c12385ddc1b34e12ae188c0131b080e0899871221159fa1ec96e7e8"

        def install
          bin.install "neetoplaydash"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v1.0.5/neeto-playdash-cli_1.0.5_linux_arm64.tar.gz"
        sha256 "b132d5276a50739cecef7788d1f640baa07a6ef06f2893d0b42dfca6b5ca52ef"

        def install
          bin.install "neetoplaydash"
        end
      end
    end
  end
end
