# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoform < Formula
  desc "NeetoForm CLI — manage forms and submissions from the terminal"
  homepage "https://neetoform.com"
  version "1.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoForm/v1.3.3/neeto-form-cli_1.3.3_darwin_amd64.tar.gz"
      sha256 "e09118c36eadb56a28e15efd488d69bc468f0e70cb4b9a4eee7e598d76c95e57"

      def install
        bin.install "neetoform"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoForm/v1.3.3/neeto-form-cli_1.3.3_darwin_arm64.tar.gz"
      sha256 "331cad0e6c5a047ee0cde6d5b15b21b1743639e547ad5df47661e3e34731e036"

      def install
        bin.install "neetoform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoForm/v1.3.3/neeto-form-cli_1.3.3_linux_amd64.tar.gz"
        sha256 "5bf07536491110b771dce4133f4d85738fac05b19bdeed2f94c545924bcf8c13"

        def install
          bin.install "neetoform"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoForm/v1.3.3/neeto-form-cli_1.3.3_linux_arm64.tar.gz"
        sha256 "3f998f38dcef977dddf3e647c7ca3859781b42901c2eb89a1bcd4f531dc34057"

        def install
          bin.install "neetoform"
        end
      end
    end
  end
end
