# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoplanner < Formula
  desc "NeetoPlanner CLI — manage projects, lists and todos from the terminal"
  homepage "https://neetoplanner.com"
  version "0.3.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoPlanner/v0.3.6/neeto-planner-cli_0.3.6_darwin_amd64.tar.gz"
      sha256 "56ba0c118a4c97279101e337e031bbd56613a5261e96cd30f9d505d2ff5f678b"

      def install
        bin.install "neetoplanner"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoPlanner/v0.3.6/neeto-planner-cli_0.3.6_darwin_arm64.tar.gz"
      sha256 "af151dd947b4416238acacda426ca9f1ee9b84a457518fd645580d32f3ca49d7"

      def install
        bin.install "neetoplanner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoPlanner/v0.3.6/neeto-planner-cli_0.3.6_linux_amd64.tar.gz"
        sha256 "fefa63e03eb1b7392054f773e46ace20df575344ac3b2e09d09c19f249b5f841"

        def install
          bin.install "neetoplanner"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoPlanner/v0.3.6/neeto-planner-cli_0.3.6_linux_arm64.tar.gz"
        sha256 "72f6a88cd390d263291170c30229612a8a5f11e1cd6fa9f0437ffb5cc0e58830"

        def install
          bin.install "neetoplanner"
        end
      end
    end
  end
end
