# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoplaydash < Formula
  desc "NeetoPlaydash CLI"
  homepage "https://neetoplaydash.com"
  version "3.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v3.0.0/neeto-playdash-cli_3.0.0_darwin_amd64.tar.gz"
      sha256 "2b515132d093711b2338dfc76d9346afb6f6f0db2e877ebd5cb9012055b4079d"

      def install
        bin.install "neetoplaydash"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v3.0.0/neeto-playdash-cli_3.0.0_darwin_arm64.tar.gz"
      sha256 "25c112553c7913a017f99e73713f4ad2b70d96b4c3c202639d4dac87ef937df7"

      def install
        bin.install "neetoplaydash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v3.0.0/neeto-playdash-cli_3.0.0_linux_amd64.tar.gz"
        sha256 "82a276687f874a637dbc8d4965f96a6ef4e630fb527c8db5ed876047e6fd704a"

        def install
          bin.install "neetoplaydash"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v3.0.0/neeto-playdash-cli_3.0.0_linux_arm64.tar.gz"
        sha256 "0040cd2bdf3aa0f29c85930b2cfddb22cfab6745143db9e42dfc7027f26a2419"

        def install
          bin.install "neetoplaydash"
        end
      end
    end
  end
end
