# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoauth < Formula
  desc "NeetoAuth CLI — manage team members and product access from the terminal"
  homepage "https://neetoauth.com"
  version "1.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoAuth/v1.3.1/neeto-auth-cli_1.3.1_darwin_amd64.tar.gz"
      sha256 "a56f63da8591077807f6349b96c81d439eb9cf2eb86bf0f781a58df903f50027"

      def install
        bin.install "neetoauth"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoAuth/v1.3.1/neeto-auth-cli_1.3.1_darwin_arm64.tar.gz"
      sha256 "a59c845e2d8bb8d34d8331bbda42c4e2d8061e393781ff1b5da1d2f045cb10da"

      def install
        bin.install "neetoauth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoAuth/v1.3.1/neeto-auth-cli_1.3.1_linux_amd64.tar.gz"
        sha256 "8b21be2e465a1e5aa413bcf36bcdcfa49644a98d233f53cc1cb3bb66d737e948"

        def install
          bin.install "neetoauth"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoAuth/v1.3.1/neeto-auth-cli_1.3.1_linux_arm64.tar.gz"
        sha256 "a090063ad8bbaf0a634893ddbdbb82cc91aec158258156b0e2687b5fa14b9f53"

        def install
          bin.install "neetoauth"
        end
      end
    end
  end
end
