# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoplanner < Formula
  desc "NeetoPlanner CLI — manage projects, lists and todos from the terminal"
  homepage "https://neetoplanner.com"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoPlanner/v0.3.1/neeto-planner-cli_0.3.1_darwin_amd64.tar.gz"
      sha256 "4ac5dc193e34318461d8b011a263840130e5f25f6492251fafde6bf67976998e"

      def install
        bin.install "neetoplanner"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoPlanner/v0.3.1/neeto-planner-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "a87d3a791c34554e3a927590a64c19cddb22a2c637fe3d7ef68d7a82d0329c15"

      def install
        bin.install "neetoplanner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoPlanner/v0.3.1/neeto-planner-cli_0.3.1_linux_amd64.tar.gz"
        sha256 "c444acf02e70b735a3ed2568397c0014d382e2d2f3963406e820a1f1eaecd9fd"

        def install
          bin.install "neetoplanner"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoPlanner/v0.3.1/neeto-planner-cli_0.3.1_linux_arm64.tar.gz"
        sha256 "b06b4792f5657180834d6f3c4380aba7f0ad7f0eacc6727cc9097f4d29f81588"

        def install
          bin.install "neetoplanner"
        end
      end
    end
  end
end
