# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetocal < Formula
  desc "NeetoCal CLI — manage your calendar from the terminal"
  homepage "https://neetocal.com"
  version "1.1.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCal/v1.1.13/neeto-cal-cli_1.1.13_darwin_amd64.tar.gz"
      sha256 "72cd3c41a7af54330aca52ebdae24863faf118e1fc81c8f24c277ddaa6079fe4"

      def install
        bin.install "neetocal"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCal/v1.1.13/neeto-cal-cli_1.1.13_darwin_arm64.tar.gz"
      sha256 "a8966fb73783511779bcf88936759f4da09ea4edc22d47af39b9421b4be1e43f"

      def install
        bin.install "neetocal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCal/v1.1.13/neeto-cal-cli_1.1.13_linux_amd64.tar.gz"
        sha256 "ade1bd97ec4ca170d057434485f19f2e606cae02720a5d245c46a3428634e598"

        def install
          bin.install "neetocal"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoCal/v1.1.13/neeto-cal-cli_1.1.13_linux_arm64.tar.gz"
        sha256 "9b1d79d415b93d4c0292003de8cc6cbc4d8174a6611bef15e2b8e647230e9648"

        def install
          bin.install "neetocal"
        end
      end
    end
  end
end
