# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoform < Formula
  desc "NeetoForm CLI"
  homepage "https://neetoform.com"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoForm/v1.0.4/neeto-form-cli_1.0.4_darwin_amd64.tar.gz"
      sha256 "e85fbefb2a3e0a7ba374fc9851cbef08632da620342f4cbdd3c61dd286179abc"

      def install
        bin.install "neetoform"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoForm/v1.0.4/neeto-form-cli_1.0.4_darwin_arm64.tar.gz"
      sha256 "b47cc74f8f484e20082d482e129f4f6811cabb48359f0351c380fedb77887190"

      def install
        bin.install "neetoform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoForm/v1.0.4/neeto-form-cli_1.0.4_linux_amd64.tar.gz"
        sha256 "aec9dc0bde227c717aa62abdc14b0b0754618d2c7efef816ed0bc9bf1d75f0de"

        def install
          bin.install "neetoform"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoForm/v1.0.4/neeto-form-cli_1.0.4_linux_arm64.tar.gz"
        sha256 "8127634c8172607d003ce4a3d2d5566c8fd35bbd5c6555c33e705aa7afb2c323"

        def install
          bin.install "neetoform"
        end
      end
    end
  end
end
