# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoci < Formula
  desc "NeetoCI CLI"
  homepage "https://neetoci.com"
  version "1.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoCI/v1.0.6/neeto-ci-cli-v2_1.0.6_darwin_amd64.tar.gz"
      sha256 "8a41c9e1af707a6e06da0fc981576dffcf6c96e1c706662bf5f93d2762636e09"

      def install
        bin.install "neetoci"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoCI/v1.0.6/neeto-ci-cli-v2_1.0.6_darwin_arm64.tar.gz"
      sha256 "a2c20f2aa70a918fd2091897b4c8d2d6416c1f7fc13efd65dc18a5229ef68f32"

      def install
        bin.install "neetoci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoCI/v1.0.6/neeto-ci-cli-v2_1.0.6_linux_amd64.tar.gz"
        sha256 "e1cc51598572742e237311d1480d7caa466954b1838a542ebcd864c03b28005d"

        def install
          bin.install "neetoci"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoCI/v1.0.6/neeto-ci-cli-v2_1.0.6_linux_arm64.tar.gz"
        sha256 "7e666831af5fa3060ed0240c1e3f3cda0e920c5bad0ff861dadf894c1d9d2e2c"

        def install
          bin.install "neetoci"
        end
      end
    end
  end
end
