# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetocal < Formula
  desc "NeetoCal CLI — manage meetings, bookings and availabilities from the terminal"
  homepage "https://neetocal.com"
  version "1.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoCal/v1.5.2/neeto-cal-cli_1.5.2_darwin_amd64.tar.gz"
      sha256 "9d2d71690cb02efeea38bc54079fea553123f69b140508c84cdd8fe16aad8a0d"

      def install
        bin.install "neetocal"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoCal/v1.5.2/neeto-cal-cli_1.5.2_darwin_arm64.tar.gz"
      sha256 "c16bcf3220699a9d96e529f0f7b38cb69780ef0c7cf4631452acc4d62abf4da8"

      def install
        bin.install "neetocal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoCal/v1.5.2/neeto-cal-cli_1.5.2_linux_amd64.tar.gz"
        sha256 "4f6d88cfbdeb1065c3b64b96667a75ce4f95c970fad416fa30c87fa96e105fbf"

        def install
          bin.install "neetocal"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoCal/v1.5.2/neeto-cal-cli_1.5.2_linux_arm64.tar.gz"
        sha256 "85a328c864a60fe2b737b7426947142d3a49a3354c7e37a4c3cc028d5d9db50b"

        def install
          bin.install "neetocal"
        end
      end
    end
  end
end
