# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoreplay < Formula
  desc "NeetoReplay CLI"
  homepage "https://neetoreplay.com"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.1/neeto-replay-cli_1.0.1_darwin_amd64.tar.gz"
      sha256 "96362dd326025107ce330fe5f8c215e8e82e49e7a0bb4f4805b0d0063e0def9d"

      def install
        bin.install "neetoreplay"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.1/neeto-replay-cli_1.0.1_darwin_arm64.tar.gz"
      sha256 "e22a1c6ae3c3751f9510cc5bcb1e81a928df38a4343ad4f51c24f0e9a855db52"

      def install
        bin.install "neetoreplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.1/neeto-replay-cli_1.0.1_linux_amd64.tar.gz"
        sha256 "b96db5a4e4752f1dacf0a57d1a547084050148d0b09e1952683bb68edd440a2e"

        def install
          bin.install "neetoreplay"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.1/neeto-replay-cli_1.0.1_linux_arm64.tar.gz"
        sha256 "0cd2c179d0ffcae2048961e16718854f899475c1fc298544194b8e35d6bc9e20"

        def install
          bin.install "neetoreplay"
        end
      end
    end
  end
end
