# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetokb < Formula
  desc "NeetoKB CLI"
  homepage "https://neetokb.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoKB/v1.0.0/neeto-kb-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "b29965e337e86d14187c6a7830d7da054e92ed9c1a4a6fc6c1cdf951c8650ab0"

      def install
        bin.install "neetokb"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoKB/v1.0.0/neeto-kb-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "1f1d9caf805fbe233731c755890435ea524785c623082efb701fe5efcdd4fd80"

      def install
        bin.install "neetokb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoKB/v1.0.0/neeto-kb-cli_1.0.0_linux_amd64.tar.gz"
        sha256 "62edec7074213743093dca277135436c23d60abeaf2cc8e0e4bce4128d961573"

        def install
          bin.install "neetokb"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoKB/v1.0.0/neeto-kb-cli_1.0.0_linux_arm64.tar.gz"
        sha256 "90c8b2455d4345f9925cd91ed4e479b2ad00e669e7ff5b0d1c48f05100933332"

        def install
          bin.install "neetokb"
        end
      end
    end
  end
end
