# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoform < Formula
  desc "NeetoForm CLI"
  homepage "https://neetoform.com"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoForm/v1.1.0/neeto-form-cli_1.1.0_darwin_amd64.tar.gz"
      sha256 "af3d26ddb94803dadd51cd600e53e48cf2ef9dab81191fdeeaf55a0c785ce8bc"

      def install
        bin.install "neetoform"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoForm/v1.1.0/neeto-form-cli_1.1.0_darwin_arm64.tar.gz"
      sha256 "de524c4a4df583782fc898321960bee9f2e454cae604cf73ea31fceaf4565ffb"

      def install
        bin.install "neetoform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoForm/v1.1.0/neeto-form-cli_1.1.0_linux_amd64.tar.gz"
        sha256 "9639e770e9cea7c532fc13a839fac594204187a69c7a2b7de6b340b118ccbdc9"

        def install
          bin.install "neetoform"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoForm/v1.1.0/neeto-form-cli_1.1.0_linux_arm64.tar.gz"
        sha256 "b7e4cdb709fa8aa702bb6c40941f18d51eba5081bd6ad33d6910b1d572c9c7d6"

        def install
          bin.install "neetoform"
        end
      end
    end
  end
end
