# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoinvoice < Formula
  desc "NeetoInvoice CLI"
  homepage "https://neetoinvoice.com"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoInvoice/v1.0.3/neeto-invoice-cli_1.0.3_darwin_amd64.tar.gz"
      sha256 "6f3366852991bf2f65e64ece51b16d03528d8c406ba25b51a72c8c82f7103935"

      def install
        bin.install "neetoinvoice"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoInvoice/v1.0.3/neeto-invoice-cli_1.0.3_darwin_arm64.tar.gz"
      sha256 "b276cf768a84e341f825da31b4e506e456d8c242ffd76c9347baac123a01ae7e"

      def install
        bin.install "neetoinvoice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoInvoice/v1.0.3/neeto-invoice-cli_1.0.3_linux_amd64.tar.gz"
        sha256 "f2c18cbbe92cbd1607f3234df83eeba8e9186d5825c68f56355013d63ef6e66e"

        def install
          bin.install "neetoinvoice"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoInvoice/v1.0.3/neeto-invoice-cli_1.0.3_linux_arm64.tar.gz"
        sha256 "4dd697023aa6592145ec88ef8c4d2585e247ff7c233329a894efd057aabd8042"

        def install
          bin.install "neetoinvoice"
        end
      end
    end
  end
end
