# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoinvoice < Formula
  desc "NeetoInvoice CLI"
  homepage "https://neetoinvoice.com"
  version "10.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoInvoice/v10.0.0/neeto-invoice-cli_10.0.0_darwin_amd64.tar.gz"
      sha256 "767b7151fa1e0ae016859f7cdf46a39d7814003caade102588be0f42ff9076f1"

      def install
        bin.install "neetoinvoice"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoInvoice/v10.0.0/neeto-invoice-cli_10.0.0_darwin_arm64.tar.gz"
      sha256 "837184aab71fb6a4511f86473db5d39a051b2bdc5c7e28a90ff8bca97d270969"

      def install
        bin.install "neetoinvoice"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoInvoice/v10.0.0/neeto-invoice-cli_10.0.0_linux_amd64.tar.gz"
        sha256 "6b222b37e3ed6c952bcad19c66ddbd54e778eaa708084b1d620b1e1a86f47d47"

        def install
          bin.install "neetoinvoice"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoInvoice/v10.0.0/neeto-invoice-cli_10.0.0_linux_arm64.tar.gz"
        sha256 "2aa1aa534bc3bc47cdd8b8e0e904136b688d6eadc99e82f1b64ba56f5c1dc0d9"

        def install
          bin.install "neetoinvoice"
        end
      end
    end
  end
end
