# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoreplay < Formula
  desc "NeetoReplay CLI"
  homepage "https://neetoreplay.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.0/neeto-replay-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "589d17f3fae660c9f0e19f9d9b6ee09795c9ee1f54a55409f235dbbb89c753ee"

      def install
        bin.install "neetoreplay"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.0/neeto-replay-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "70a9895b637ee7f264af108508b1c5bf3ca41e497d991e7d25924abf154d3c3b"

      def install
        bin.install "neetoreplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.0/neeto-replay-cli_1.0.0_linux_amd64.tar.gz"
        sha256 "21cbc60756e47552464413fc8e69ba44e764afcb46337c8f7447ef967fa475cb"

        def install
          bin.install "neetoreplay"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.0/neeto-replay-cli_1.0.0_linux_arm64.tar.gz"
        sha256 "7793deaf81e63a8c6784d340f819fdec8ee954335205d477754ba9e7ef96c167"

        def install
          bin.install "neetoreplay"
        end
      end
    end
  end
end
