# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoplaydash < Formula
  desc "NeetoPlaydash CLI"
  homepage "https://neetoplaydash.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v1.0.0/neeto-playdash-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "1785aa24f337cbeb65213028a930611539f33bae532959db76c3890d8f8cc77c"

      def install
        bin.install "neetoplaydash"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v1.0.0/neeto-playdash-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "b9857c0629ad850729b73689c003cfe9cba0c1c6bccbe7e99499f3a5c948626e"

      def install
        bin.install "neetoplaydash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v1.0.0/neeto-playdash-cli_1.0.0_linux_amd64.tar.gz"
        sha256 "ab29a81fca5139d936d0e8244386aceb1b70e3ef77fffefcc25a9bb2010c3202"

        def install
          bin.install "neetoplaydash"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoPlaydash/v1.0.0/neeto-playdash-cli_1.0.0_linux_arm64.tar.gz"
        sha256 "53031d9c948d80b067c07707e5dc5516c352eb111374e5ea449c1a5e9b3e57ef"

        def install
          bin.install "neetoplaydash"
        end
      end
    end
  end
end
