# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoauth < Formula
  desc "Command-line interface for NeetoAuth team member management."
  homepage "https://neetoauth.com"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v1.0.0/neeto-auth-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "2a7290de864002abe1608ae81e74f738b2f494cda9dd5d9e7dd3434edd81445e"

      def install
        bin.install "neetoauth"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v1.0.0/neeto-auth-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "7e9c3c49e1e73bac4a2c3401b752919f6db75b76d1d25b3f192b52ff17b8ab20"

      def install
        bin.install "neetoauth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v1.0.0/neeto-auth-cli_1.0.0_linux_amd64.tar.gz"
        sha256 "8551f835801f8b9d7c4404d172c28404ce67091a835316168eb977a1f6df5894"

        def install
          bin.install "neetoauth"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoAuth/v1.0.0/neeto-auth-cli_1.0.0_linux_arm64.tar.gz"
        sha256 "5f43dd758ef7fb32b856af1af1a47d27c38eecf4f30bc515b3eabf9db9fe911a"

        def install
          bin.install "neetoauth"
        end
      end
    end
  end
end
