# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetodesk < Formula
  desc "NeetoDesk CLI"
  homepage "https://neetodesk.com"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoDesk/v1.0.1/neeto-desk-cli_1.0.1_darwin_amd64.tar.gz"
      sha256 "59d848ff48dfbf4d65455e6f7c66f70c4607b3891fc5b20cccae96ea0a50950f"

      def install
        bin.install "neetodesk"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoDesk/v1.0.1/neeto-desk-cli_1.0.1_darwin_arm64.tar.gz"
      sha256 "13ce6253a011e1cfb8b24ca8c5a66d2d2751891303123608ad76e9e4c0179ca2"

      def install
        bin.install "neetodesk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoDesk/v1.0.1/neeto-desk-cli_1.0.1_linux_amd64.tar.gz"
        sha256 "8157b9eaf42fa33e9a45e442f2d9f7bde793eed0e98f10c059ceceb4a27db5a4"

        def install
          bin.install "neetodesk"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoDesk/v1.0.1/neeto-desk-cli_1.0.1_linux_arm64.tar.gz"
        sha256 "4cd45d74e77e52b26190138956081549bbc017a1901d3ed10cb05a64fbbb0ef7"

        def install
          bin.install "neetodesk"
        end
      end
    end
  end
end
