# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetorecord < Formula
  desc "NeetoRecord CLI — manage recordings, folders and tags from the terminal"
  homepage "https://neetorecord.com"
  version "1.4.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoRecord/v1.4.3/neeto-record-cli_1.4.3_darwin_amd64.tar.gz"
      sha256 "5295fbc87d86275f6a3debe7b9f87b194245d8c74373e68e875ed2460d2646e0"

      def install
        bin.install "neetorecord"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoRecord/v1.4.3/neeto-record-cli_1.4.3_darwin_arm64.tar.gz"
      sha256 "612dc5b72a8215210726ba48b5b1c848cb88071e324d922f3378699a0b273764"

      def install
        bin.install "neetorecord"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoRecord/v1.4.3/neeto-record-cli_1.4.3_linux_amd64.tar.gz"
        sha256 "2ad36dea08aad31f806e10fd6eb49b40b90899a8b6f1810664b35534be316a4b"

        def install
          bin.install "neetorecord"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoRecord/v1.4.3/neeto-record-cli_1.4.3_linux_arm64.tar.gz"
        sha256 "d1285a699bee91d6cd3e0e12d8bb088b4fe4a219dbc4a8bca2b2facd71529706"

        def install
          bin.install "neetorecord"
        end
      end
    end
  end
end
