# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoci < Formula
  desc "NeetoCI CLI"
  homepage "https://neetoci.com"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoCI/v1.1.0/neeto-ci-cli-v2_1.1.0_darwin_amd64.tar.gz"
      sha256 "eecb0a12e47656d135809b6d07745825ac7b04347173b4afd9fe0fc5df82bf00"

      def install
        bin.install "neetoci"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoCI/v1.1.0/neeto-ci-cli-v2_1.1.0_darwin_arm64.tar.gz"
      sha256 "6f4d052578d4575cea280767c92166001206932d424778b9117f940e3bc52556"

      def install
        bin.install "neetoci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoCI/v1.1.0/neeto-ci-cli-v2_1.1.0_linux_amd64.tar.gz"
        sha256 "c2cdc2fb6e13e1a60fdc829b17536642245a2dc502c837ef425832d850fbaba0"

        def install
          bin.install "neetoci"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoCI/v1.1.0/neeto-ci-cli-v2_1.1.0_linux_arm64.tar.gz"
        sha256 "28fb40bfd55e52a4e7b1e3bd55c497459f95708c010b0f38d82f2d39482e075a"

        def install
          bin.install "neetoci"
        end
      end
    end
  end
end
