# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoengage < Formula
  desc "NeetoEngage CLI"
  homepage "https://neetoengage.com"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoEngage/v1.1.0/neeto-engage-cli_1.1.0_darwin_amd64.tar.gz"
      sha256 "d73cf7b6f5f43dcbad75b8083030ae68a0ed6dc91bcd6757f9a0cfd09597fe91"

      def install
        bin.install "neetoengage"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoEngage/v1.1.0/neeto-engage-cli_1.1.0_darwin_arm64.tar.gz"
      sha256 "abce7c3111de7fec73370755803a63fd3476d152cd17cf536d858ae780005fdb"

      def install
        bin.install "neetoengage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoEngage/v1.1.0/neeto-engage-cli_1.1.0_linux_amd64.tar.gz"
        sha256 "fba505404bc5795deb826a798ead49a8e25324221f7af1d7216a329a4bd08c71"

        def install
          bin.install "neetoengage"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoEngage/v1.1.0/neeto-engage-cli_1.1.0_linux_arm64.tar.gz"
        sha256 "1211c094d68f2f9f4173eda84d3e2898e1f5fefa2cbc6872aa7202eb07447ccc"

        def install
          bin.install "neetoengage"
        end
      end
    end
  end
end
