# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetoreplay < Formula
  desc "NeetoReplay CLI"
  homepage "https://neetoreplay.com"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.2/neeto-replay-cli_1.0.2_darwin_amd64.tar.gz"
      sha256 "478984c8857650600fd61d42c166e1f0fe4344f6a6d1add520b7abb83589ac29"

      def install
        bin.install "neetoreplay"
      end
    end
    if Hardware::CPU.arm?
      url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.2/neeto-replay-cli_1.0.2_darwin_arm64.tar.gz"
      sha256 "2d4f56e507b385dbb7fb75a62c0f59a3f4634e1b9f15766d7f5628b546be0435"

      def install
        bin.install "neetoreplay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.2/neeto-replay-cli_1.0.2_linux_amd64.tar.gz"
        sha256 "74054c330baa2c47a735064b6ecd2b4de789d658a3c45e0480f149b1e9307f34"

        def install
          bin.install "neetoreplay"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://downloads.neeto.com/cli/NeetoReplay/v1.0.2/neeto-replay-cli_1.0.2_linux_arm64.tar.gz"
        sha256 "95850309feaf37ec1b3ecc8a06ceb1bad844aee3b353feefdce8e2f2254c8b25"

        def install
          bin.install "neetoreplay"
        end
      end
    end
  end
end
