# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neetokb < Formula
  desc "NeetoKB CLI"
  homepage "https://neetokb.com"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoKB/v1.0.4/neeto-kb-cli_1.0.4_darwin_amd64.tar.gz"
      sha256 "41d22988b65b4820ba8c102fd4c1fc6f7a9378be022ece55f8a0362ca0292a1a"

      def install
        bin.install "neetokb"
      end
    end
    if Hardware::CPU.arm?
      url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoKB/v1.0.4/neeto-kb-cli_1.0.4_darwin_arm64.tar.gz"
      sha256 "94d5f3a31f8caec1ab417cd5e04ce201737323ce8fca21d6d7f0bd4ab80ed099"

      def install
        bin.install "neetokb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoKB/v1.0.4/neeto-kb-cli_1.0.4_linux_amd64.tar.gz"
        sha256 "28668023ceebc962cd1017e5fb2db953b6466774589cda1f570fdcf641d38787"

        def install
          bin.install "neetokb"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://neeto-downloads.s3.amazonaws.com/cli/NeetoKB/v1.0.4/neeto-kb-cli_1.0.4_linux_arm64.tar.gz"
        sha256 "3d7a750a604a312158ca1ba49ae2e21e39c5e3027256eaa069f4a0ddd4fae973"

        def install
          bin.install "neetokb"
        end
      end
    end
  end
end
